services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4324
      POSTGRES_DB: podarkiuz
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    container_name: podarki-uz-backend
    build:
      context: .
      dockerfile: Dockerfile
    image: podarkiuz-app
    ports:
      - '3001:3001'
    depends_on:
      - postgres

volumes:
  postgres-data:
