name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./podarki-uz-backend
          file: ./podarki-uz-backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/podarki-uz-backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: 22
          script: |
            cd ~/projects/podarki-uz
            git pull origin main

            # Pull latest Docker images
            docker pull ${{ secrets.DOCKER_USERNAME }}/podarki-uz-backend:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/podarki-uz-frontend:latest

            # Stop and remove existing containers
            docker-compose down

            # Start containers with updated images
            docker-compose up -d --build
